### ISSUE TITLE
Documentation example typo "Get #US stream strings"

### ISSUE THREAD

**Issue by julupu** [pan-unit42/dotnetfile#6]
The example for get_user_stream_strings() (https://pan-unit42.github.io/dotnetfile/api_documentation/general/#get-us-stream-strings) seems to have a typo in the example in line 8 "get_us_stream_strings()" ("us" instead of "user"):

`us_stream_strings = dotnet_file.get_us_stream_strings()`

Leading to the error:

`AttributeError: 'DotNetPE' object has no attribute 'get_us_stream_strings'`

It's correct slightly above at the definition.

**Comment by TheEnergyStory** [comment]
Thanks for your contribution, this has been fixed in version 0.2.4
